

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###

POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Pasang",
    "dateOfBirth": "2000.12.07",
    "ssn": "12345678-XXXX",
    "gender": "test",
    "occupation": "Developer"
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "MOHKO",
    "date": "2022-02-15",
    "specialist": "Mohko-doctor"
}


